### PR TITLE
feat: add Sylius 1.12 support

### PR DESCRIPTION
**Pull request by DjLeChuck**
- PHP ^8.0
- Symfony ^5.4|^6.0

### CODE REVIEW

**Comment by loevgaard** [comment]
Hi, @DjLeChuck 

Appreciate the PR :-)

1. Can you only change the necessary deps. I guess it's only the Symfony deps and change them to `^5.4 || ^6.0`
2. In the code, please only fix the changes regarding main/master request so that we won't have any breaking changes

Thank you :-)

**Comment by DjLeChuck** [comment]
Hi @loevgaard 

It’s done, but two remarks:
* I have let the change of `getMainRequest()` because `getMasterRequest()` is deprecated since Symfony 5.3, so using `getMainRequest()` is not a BC Break ;
* I have remove `use function Safe\sprintf;` usage, I think it’s was mistake in the code and it’s spamming the logs

**Comment by loevgaard** [comment]
Great work, @DjLeChuck. Thank you 🎉

**Comment by GeneraleCauchemar** [comment]
Hi @loevgaard , thank you for merging this PR! I'm a colleague of @DjLeChuck , we use this plugin in one of our Sylius projects we are upgrading to Symfony 6.3, hence the PR.
Could you maybe publish a new version tag so we can go back to using this plugin instead of our fork?

Many thanks in advance

**Comment by loevgaard** [comment]
Done, @GeneraleCauchemar :)

**Comment by etrange02** [comment]
Hi,
There is still a bug on this PR.
In src/Resources/config/routes/shop.yaml, it must be _controller: sylius.controller.product::showAction instead of _controller: sylius.controller.product:showAction (':' must be doubled)

I am working on php 8.1 and symfony 6.2

**Comment by loevgaard** [comment]
@etrange02: Please make a PR and fix it :)

**Pull request merged**
